#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run path-test
npm run headless-browser-path-test
npm run link-local-moka
npm run import-test
npm run headless-browser-test
#npm run build-commonjs
#npm run require-test
npm run build-docs
npm run build-types
npm run add-generated-files-to-commit
